#!/bin/bash
#
# This script wraps git, so install it somewhere such as ~/bin where
# it will be found by your shell before the actual git executable.
# Based on:
# https://gist.github.com/mmueller/7286919

set -e

GIT_CMDS=("add" "config" "get-tar-commit-id" "merge-ours" "remote" "show-ref"
          "add--interactive" "count-objects" "grep" "merge-recursive" "remote-ext" "stage"
          "am" "credential" "hash-object" "merge-resolve" "remote-fd" "stash"
          "annotate" "credential-cache" "help" "merge-subtree" "remote-ftp" "status"
          "apply" "credential-cache--daemon" "http-backend" "merge-tree" "remote-ftps" "stripspace"
          "archive" "credential-store"http-fetch" "mergetool" "remote-http" "submodule"
          "bisect" "daemon"http-push" "mktag" "remote-https" "submodule--helper"
          "bisect--helper" "describe"imap-send" "mktree" "remote-testsvn" "subtree"
          "blame" "diff"index-pack" "mv" "repack" "symbolic-ref"
          "branch" "diff-files"init" "name-rev" "replace" "tag"
          "bundle" "diff-index"init-db" "notes" "request-pull" "unpack-file"
          "cat-file" "diff-tree"instaweb" "pack-objects" "rerere" "unpack-objects"
          "check-attr" "difftool"interpret-trailers" "pack-redundant" "reset" "update-index"
          "check-ignore" "difftool--helper"log" "pack-refs" "rev-list" "update-ref"
          "check-mailmap" "fast-export"ls-files" "patch-id" "rev-parse" "update-server-info"
          "check-ref-format" "fast-import"ls-remote" "prune" "revert" "upload-archive"
          "checkout" "fetch"ls-tree" "prune-packed" "rm" "upload-pack"
          "checkout-index" "fetch-pack"mailinfo" "pull" "send-email" "var"
          "cherry" "filter-branch"mailsplit" "push" "send-pack" "verify-commit"
          "cherry-pick" "fmt-merge-msg"merge" "quiltimport" "sh-i18n--envsubst" "verify-pack"
          "clean" "for-each-ref"merge-base" "read-tree" "shell" "verify-tag"
          "clone" "format-patch" "merge-file" "rebase" "shortlog" "web--browse"
          "column" "fsck" "merge-index" "receive-pack" "show" "whatchanged"
          "commit" "fsck-objects" "merge-octopus" "reflog" "show-branch" "worktree"
          "commit-tree" "gc" "merge-one-file" "relink" "show-index" "write-tree")
PRE="[git-wrapper]"

# Extract the command from a git command line
function get_command {
    while [[ "$1" =~ ^- ]]; do
        echo $1
        shift
    done

    for cmd in "${GIT_CMDS[@]}"; do
        if [ "$cmd" == "$1" ]; then
            echo "$1"
            return
        fi
	done
 
    # Look up command in git alias
    local alias="$("$GIT" config -l | grep "alias."$1"=")"
    if [ "$alias" != "" ]; then
        local command="${alias#*=}"
    fi
    echo "$command"
}

function pre_command {
    local command="$(get_command "$@")"
    
    # Pre-command hooks could go here
    case "$command" in
        commit) pre_commit "$@" ;;
    esac
}

function pre_commit {
    if [ -n "${GIT_WRAPPER_ALLOWDETACHED}" ]; then
        return
    fi
    
    set +e
    local branch_name="$("$GIT" symbolic-ref HEAD 2>/dev/null)"
    set -e
    if [ -z "$branch_name" ]; then
        echo ""$PRE" WARNING: HEAD detached"
        echo ""$PRE" You have to checkout a branch before you can commit."
        echo ""$PRE" Disable this check by setting GIT_WRAPPER_ALLOWDETACHED to a nonempty value."
        exit
    fi    
}

function post_command {
    command="$(get_command "$@")"

    # Post-command hooks
    case $command in
        commit) post_commit "$@";;
        pull) post_checkout "$@";;
        merge) post_checkout "$@";;
        checkout) post_checkout "$@";;
    esac
}

function post_checkout {
    local diff="$("$GIT" diff --submodule)"
    if [ "$diff" != "" ]; then
        echo
        echo ""$PRE" WARNING: One or more submodules do not match the SHA-1 found in the index"
        echo ""$PRE"   (use \"git submodule update\" to checkout the submodules)"
        return
    fi
}

function post_commit {
    if [ -n "${GIT_WRAPPER_NOPARENTCOMMIT}" ]; then
        return
    fi
	
    local git_dir="$("$GIT" rev-parse --git-dir 2>/dev/null)"
    if [ -z "$git_dir" ]; then
        echo ""$PRE" ERROR: \"git rev-parse --git-dir\" failed!"
        exit
    fi  
    
    local submodule_name="$(basename "$git_dir")"
    if [ "$submodule_name" == ".git" ]; then
        return
    fi

    local parent_top="${git_dir%.git*}"
    local parent_name="$(basename "$parent_top")"
    local parent_branch="$("$GIT" -C "$parent_top" symbolic-ref --short HEAD 2>/dev/null)"
    echo
    echo ""$PRE" You just commited to the submodule: '"$submodule_name"'"
	echo ""$PRE" Do you wish to update the parent repo to this commit?"
    echo ""$PRE" name:   "$parent_name""
    echo ""$PRE" branch: "$parent_branch""
    echo ""$PRE" (set GIT_WRAPPER_NOPARENTCOMMIT to a nonempty value to never ask again)"
    while true; do
        read -p ""$PRE" This will require to push your changes first. [y/n] " yn
        case $yn in
            y ) local submodule_top="${git_dir#*modules/}"
                local commit_message="["$submodule_name"] "$("$GIT" log --pretty=format:'%s' | head -n1)""
                push_submodule
                commit_parent "$parent_top" "$commit_message" "$submodule_top"
                push_parent "$parent_top"
                break;;
            n ) return;;
            * ) echo "Please answer y or n.";;
        esac
    done
}

function push_parent {
    echo
    echo ""$PRE" pushing parent..."
    local parent_branch parent_top info
    parent_top="$1"
    parent_branch="$("$GIT" -C "$parent_top" symbolic-ref --short HEAD 2>/dev/null)"
    echo ""$PS4"git -C "$parent_top" push origin "$parent_branch""
    set +e
    info="$("$GIT" -C "$parent_top" push origin "$parent_branch" 2>&1)"
    set -e
    echo "$info"
    if [ "${info#*error}" != "$info" ]; then
        echo ""$PRE" ERROR: pushing parent failed!"
        echo ""$PRE" Try to manually push your changes."
        exit
    fi
}

function push_submodule {
    echo
    echo ""$PRE" pushing submodule..."
    local submodule_branch info
    submodule_branch="$("$GIT" symbolic-ref --short HEAD 2>/dev/null)"
    echo ""$PS4"git push origin "$submodule_branch""
    set +e
    info="$("$GIT" push origin "$submodule_branch" 2>&1)"
    set -e
    echo "$info"
    if [ "${info#*error}" != "$info" ]; then
        echo ""$PRE" ERROR: pushing submodule failed!"
        echo ""$PRE" Try to manually push your changes."
        exit
    fi
}

function commit_parent {
    echo
    echo ""$PRE" commiting parent..."
    local parent_top commit_message submodule_top
    parent_top="$1"
    commit_message="$2"
    submodule_top="$3"
    echo ""$PS4"git -C "$parent_top" commit -m '"$commit_message"' -- "$submodule_top""
    "$GIT" -C "$parent_top" commit -m "$commit_message" -- "$submodule_top"
}

# Assuming this script is called 'git', find the next available 'git' command
# via 'which'. Override this if you want to hard-code a different path.
GIT="`which -a git | awk 'NR==2 {print}'`"
if [ "$GIT" = "" ]; then
    echo "git executable not found"
    exit 1
fi

# General: Do not run hooks for --help
if [ "${@: -1}" == "--help" ]; then
    "$GIT" "$@"
else
    pre_command "$@"
    "$GIT" "$@"
    post_command "$@"
fi

